### ISSUE TITLE
关于表格渲染

### ISSUE THREAD

**Issue by wen-bao** [pagecho/maupassant#15]
对于表格渲染有问题，解决方法为在style.css中添加
```css
table {
    width: 100%;
    border: 1px solid #e1e1e1;
    border-collapse: collapse;
}
table thead {
    background-color: #f7f7f7;
}
table th,table td {
    color: #444;
    padding: .5rem;
    border: 1px solid #e1e1e1;
}
table tr {
    transition: background-color .3s;
}
table tr:hover {
    background-color: #f8f8f8;
}
```
